config/routes.rb
Rails.application.routes.draw do
  resources :employees, only: %i[index show]
  root 'employees#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee 
  attr_reader :id, :email, :first_name, :last_name, :avatar

  def initialize(attributes = {})
    @email = attributes[:email]
    @first_name = attributes[:first_name]
    @last_name = attributes[:last_name]
    @avatar = attributes[:avatar]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = EmployeeClient.all
  end

  def show
    @employee = EmployeeClient.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/index.html.erb
<h1>Employees List</h1>
<ul>
  <% @employees.each do |employee| %>
    <li><%= link_to "#{employee[:first_name]} #{employee[:last_name]}", employee_path(employee[:id]) %></li>
  <% end %>
</ul>

app/views/employees/show.html.erb
<%= image_tag(@employee.avatar) %>
<h1><%= @employee.first_name %> <%= @employee.last_name %></h1>
<p>Email: <%= @employee.email %></p>
<li><%= link_to "Back", root_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Theoffice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>